language: java
before_install:
- openssl aes-256-cbc -K $encrypted_f78c5c4b566c_key -iv $encrypted_f78c5c4b566c_iv
  -in gradle.properties.enc -out gradle.properties -d
after_success:
- "./gradlew jacocoTestReport coveralls"
